@extends('layouts.app')
@section('title','Chart Generation Audit')
@section('content')
<div class="container py-5">
    <h1 class="mb-4">Chart Generation Audit</h1>

    <!-- Summary Cards -->
    <div class="row mb-4">
        <div class="col-md-4">
            <div class="card text-bg-primary">
                <div class="card-body">
                    <h5 class="card-title">Total Charts Generated</h5>
                    <h2 class="mb-0">{{ number_format($totalCharts) }}</h2>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card text-bg-success">
                <div class="card-body">
                    <h5 class="card-title">Active Users</h5>
                    <h2 class="mb-0">{{ number_format($totalUsers) }}</h2>
                    <small class="text-white-50">Users who generated charts</small>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card text-bg-info">
                <div class="card-body">
                    <h5 class="card-title">Charts This Month</h5>
                    <h2 class="mb-0">{{ number_format($chartsThisMonth) }}</h2>
                    <small class="text-white-50">{{ now()->format('F Y') }}</small>
                </div>
            </div>
        </div>
    </div>

    <!-- Per-Client Statistics -->
    <div class="card mb-4">
        <div class="card-header">
            <h5 class="mb-0">Charts Generated by Client</h5>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>Client Name</th>
                            <th>Email</th>
                            <th>Company</th>
                            <th class="text-end">Total Charts</th>
                            <th>Last Generated</th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse($stats as $stat)
                            <tr>
                                <td>{{ $stat->name }}</td>
                                <td>{{ $stat->email }}</td>
                                <td>{{ $stat->company_name ?? '-' }}</td>
                                <td class="text-end">
                                    <strong>{{ number_format($stat->total_charts) }}</strong>
                                </td>
                                <td>
                                    @if($stat->last_generated)
                                        {{ \Carbon\Carbon::parse($stat->last_generated)->format('M d, Y g:i A') }}
                                        <br>
                                        <small class="text-muted">{{ \Carbon\Carbon::parse($stat->last_generated)->diffForHumans() }}</small>
                                    @else
                                        <span class="text-muted">Never</span>
                                    @endif
                                </td>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="5" class="text-center text-muted">No data available</td>
                            </tr>
                        @endforelse
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <!-- Recent Generations -->
    <div class="card">
        <div class="card-header">
            <h5 class="mb-0">Recent Chart Generations (Last 20)</h5>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-sm">
                    <thead>
                        <tr>
                            <th>Date & Time</th>
                            <th>User</th>
                            <th>Start Date</th>
                            <th>Surgery Date</th>
                            <th class="text-center">Medications</th>
                            <th class="text-center">Days</th>
                            <th class="text-center">Format</th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse($recentGenerations as $generation)
                            <tr>
                                <td>
                                    {{ $generation->created_at->format('M d, Y') }}<br>
                                    <small class="text-muted">{{ $generation->created_at->format('g:i A') }}</small>
                                </td>
                                <td>
                                    {{ $generation->user->name }}<br>
                                    <small class="text-muted">{{ $generation->user->email }}</small>
                                </td>
                                <td>{{ $generation->start_date->format('M d, Y') }}</td>
                                <td>{{ $generation->surgery_date ? $generation->surgery_date->format('M d, Y') : '-' }}</td>
                                <td class="text-center">{{ $generation->medication_count }}</td>
                                <td class="text-center">{{ $generation->total_days }}</td>
                                <td class="text-center">
                                    <span class="badge {{ $generation->format === 'pdf' ? 'bg-primary' : 'bg-secondary' }}">
                                        {{ strtoupper($generation->format) }}
                                    </span>
                                </td>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="7" class="text-center text-muted">No generations yet</td>
                            </tr>
                        @endforelse
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection
